### ISSUE TITLE
provide upcoming webinar URLs etc on https://www.repronim.org/webinar-series.html

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/repronim.github.io#120]

**Comment by chaselgrove** [comment]
Appears to have been kept up to date (thanks, @juliebates !).

**Comment by juliebates** [comment]
Oh phew, I thought I had kept up on that 😉 not behind somewhere, anywhere, is a good feeling!

From: chaselgrove ***@***.***>
Date: Tuesday, July 30, 2024 at 3:29 PM
To: ReproNim/repronim.github.io ***@***.***>
Cc: Bates, Julianna (Julie) ***@***.***>, Mention ***@***.***>
Subject: Re: [ReproNim/repronim.github.io] provide upcoming webinar URLs etc on https://www.repronim.org/webinar-series.html (#120)

Appears to have been kept up to date (thanks, @juliebates<https://github.com/juliebates> !).
