### ISSUE TITLE
Assign a responsible person to maintain the website

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/repronim.github.io#133]
There is a growing number of issues reported against the website.  Some we had fixed "collectively".  Updates do come in from people providing news etc. But there seems to be no dedicated person to take care about our website. Some fixes do require time of someone, ideally with knowledge of the original setup for the website (plain html instead of some platform) and/or interest in web tech, to be assigned and have them addressed.  If no such person is found within ReproTeam, I guess we could issue an external call and seek assistance from some contractors/students/interns to make it happen.

**Comment by chaselgrove** [comment]
I've assigned this issue to myself, the assignment being to assign a responsible person.  And having taken responsibility for this ticket I hereby assign that to myself.

After discussion with @juliebates, the general approach will be:

- I'll manage issues to this repo, both existing and future.  Given that this site is approaching its end of life and will soon be replaced, triage will be fairly severe.
- You should feel free to merge changes at will.  You're also welcome to request a PR review from me if you'd like.

I'll see that the new web site has a better change policy in place than we've had here.
