### ISSUE TITLE
my recent webinar is missing

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/repronim.github.io#150]
Given in Dec on 'Reproducible Execution of Data Collection/Processing'.  Thought to point to our page https://www.repronim.org/webinar-series.html for the ultimate pointer to it but apparently it is missing and I started doubting I ever gave it ;)

**Comment by juliebates** [comment]
Ahh, you are right! I’m so sorry! it is still on main page of site, not there
I will fix it! Thanks for alerting me, there are so many busy distractions right now 😉

By the way also, regarding your webinar, would you be able to either send to me OR put a copy of your slide set, not just a link (in pdf or ppt, or google slides, whatever is convenient) into the December2020 folder which is here: https://drive.google.com/drive/folders/1yNdnxQ_hjRz-I-T5fluMWB9TiWMdWpLV
ReproNim_Public >  ReproNimWebinar > December2020-DataCollection/Processing

The link I have for your slides is very good for viewing,  http://datasets.datalad.org/centerforopenneuroscience/nuisance/presentations/2020-NNL/#/  but Dave aims to keep a ‘hard copy’ set in the Webinars folder, and for some reason neither one of us was able to PDF-ify from that link. (there are lots of reasons why it might not work for me, but I think he usually has a way)

**Comment by juliebates** [comment]
It really happened after all 😉,  such a good talk, too.
Webinars page has been updated, I owe you one!

**Comment by yarikoptic** [comment]
> The link I have for your slides is very good for viewing, http://datasets.datalad.org/centerforopenneuroscience/nuisance/presentations/2020-NNL/#/

see -- too many talks/slides... That is another one ;)  http://datasets.datalad.org/repronim/artwork/talks/webinar-2020-reprocomp/#/ is the correct one.  Unfortunately http://datasets.datalad.org/repronim/artwork/talks/webinar-2020-reprocomp/?print-pdf#/ makes it "not good" so cannot provide PDF ATM... may be I should just upload a .zip file with the entirety of "sources"? ;)

**Comment by juliebates** [comment]
😉
Oops, good catch, I’ll change the link for your slide presentation!

It looks like other talk is referenced in your README file as your slides setup for the ReproNim webinar. Good cross-talking for some viewers to give them more than one cool thing to think about…but I’m not quite sure how to solve in the long run 😉 That will probably be a kennedy.dave question sometime after 1/25, we can certainly put a document with a link to the ‘live’ version in the webinarfolder file, but when I asked him about that before he said he did really want to keep a slideset for each. I could probably do something really simple-minded and do a series of screen shots or something…but …not this week!

**Comment by yarikoptic** [comment]
it seems that webinar is listed now
```
$> git grep reprocomp
webinar-series.html:                           <li><a href="https://youtu.be/dwBtrpI2iS0">Video Presentation</a> and <a href="http://datasets.datalad.org/repronim/artwork/talks/webinar-2020-reprocomp/#/">Slides</a> are now available.
```
so let's consider the issue addressed.
