### ISSUE TITLE
A list(ing) of collaborator and service projects

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/repronim.github.io#19]
Collaborating projects
- [ ] DataLad
- [ ] BIDS
- [ ] ...

**Comment by chaselgrove** [comment]
The official collaborator and service projects are linked from the Community section on the front page.  Is this what you're after, or something more?

**Comment by yarikoptic** [comment]
I was blind (or website didn't make it easy to find - no top menu/overview ): http://www.reproducibleimaging.org/community.html
