### ISSUE TITLE
Main page top bar navigation links

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/repronim.github.io#25]
Wondering if it's possible to have the main ReproNim page top bar have navigation links to the various segments of the page/site...

**Comment by chaselgrove** [comment]
When all the project pages have basic content, we'll add these back.  It's no good having links to pages with my bogus placeholders!

**Comment by yarikoptic** [comment]
FWIW -- "Do" is in place now

**Comment by dnkennedy** [comment]
OK, the top bar is active now...
