### ISSUE TITLE
Make it easier to navigate to each specific training module

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/repronim.github.io#4]
Currently just points to http://www.reproducibleimaging.org/module-intro, IMHO could link to all of the existing ones

**Comment by chaselgrove** [comment]
Maybe hold off on anything on this page -- I'll be replacing it soon.

Don't forget also that we have training.repronim.org.

**Comment by chaselgrove** [comment]
Fixed by #5 ?

**Comment by yarikoptic** [comment]
Yes
