### ISSUE TITLE
hideous rendition of a wonderful figure on the main landing page

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/repronim.github.io#41]
That is how it looks to me (actually I managed to cut off the title which is also subpar) in Mozilla Firefox 64.0 on Debian :
![gkrellShoot_04-04-19_220022](https://user-images.githubusercontent.com/39889/55599406-a3801f00-5725-11e9-8993-cd88ee79986d.png)

If it is to be an SVG, trace all text/fonts to become regular paths, so it wouldn't depend on fonts availability on the visiting computer/browser.

Also while at it please rename NICEMAN to ReproMan!

**Comment by dnkennedy** [comment]
Is this concern overtaken by the updated site now?

**Comment by yarikoptic** [comment]
is that figure still anywhere on the website? couldn't find it on a quick browse

**Comment by dnkennedy** [comment]
I think it's gone from the site, but could be revived, if you want it somewhere...

**Comment by chaselgrove** [comment]
No longer relevant.  Closing.
